server:
  port: 80
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://192.168.1.114:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&autoReconnect=true&useSSL=false
    username: keveon
    password: keveon
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
logging:
  level:
    com.keveon: trace
    com.mysql: warn
    org.hibernate: warn
    org.springframework: warn

